### ISSUE TITLE
🎨 Background overlay is not styled!

### ISSUE THREAD

**Issue by dion-ricky** [dion-ricky/orion-switch#1]
When the JavaScript function `sidebar_open` is called, HTML object called `myOverlay` will be set to block style (default is none). But when I debug it on Chrome v61.0.3163 it doesn't work. Help me solving the problem! You can look up at [orion-switch/inventory/index.php](../blob/master/inventory/index.php)

**Comment by Stranger** [comment]
```
function sidebar_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}
function sidebar_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}

```
Just looking at the code to begin with, why does the `sidebar_close()` function exist? You can just set the `sidebar_open()` function on the close button and it will work the same way. Change the name of the `sidebar_open()` function to be more appropriate.

The reason it's not working is because you're using getElementById on an element (myOverlay) that doesn't exist yet in the DOM, the <script> tag is before the HTML element has been parsed.

Also, putting the <script> in the middle of the HTML like that is bad practice, as it will stop parsing the HTML till the script has finished executing.

**Comment by dion-ricky** [comment]
@Stranger Thanks for your answer also for your advice. I've changed the position of the script and I also delete `sidebar_close()` then I change `sidebar_open()` to `sidebar()`. And it works, thanks... 🎉 👍
